name: Feature request
description: Suggest an idea!
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time out of your day to help make this project better for all! 🩵
        If you prefer talking directly with us, head on over to our [support server](https://thatskyapplication.com/support)!
  - type: textarea
    attributes:
      label: Feature request
      description: Type out your idea~
    validations:
      required: true
